import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BackgroundPattern from "@/components/BackgroundPattern";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  min-h-screen bg-[#e5e8ec] `}>
        <BackgroundPattern />
        <div className="mx-auto max-w-[1200px]">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
